spring:
  application:
    name: PrismWeather
  datasource:
    url: jdbc:mysql://localhost:3306/prismweather
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

security:
  jwt:
    secret: "abcdabcd12341234567890abcdefghijklmnopqrstuvwxyz"
    expiration-ms: 86400000

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.mehedi.prismweather: DEBUG
    org.hibernate.SQL: DEBUG
