global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

## Load rules once and periodically evaluate them
rule_files:
  - "/etc/prometheus/rules/recording_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'redis'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['redis-exporter:9121']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'redis'

  - job_name: 'mysql'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['mysqld-exporter:9104']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'mysql'

  - job_name: 'spring-app'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'prismweather'
